In [1]:
import numpy as np

In [3]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [9]:
data =np.random.rand(3,4)


reshaped_data = data.reshape(10, 2)

ValueError: cannot reshape array of size 12 into shape (10,2)

In [8]:
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
reshaped_data

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.random.normal(0, 1, 100)

array([-0.60736376,  0.32022779, -0.63359814, -0.23232934, -1.05015308,
       -0.15278646, -3.21908587, -0.33803673, -0.87906477, -0.98451503,
       -0.71096765, -0.44902152, -0.00747717, -0.64613791,  0.67516775,
        0.34547318, -0.81348797, -0.10691235,  0.20236633,  1.36797148,
        0.12500341, -0.7270446 , -0.12556853,  2.84928999, -0.24739048,
       -0.18117912,  0.64615686,  0.88475921,  0.11996605, -0.22825886,
       -0.23871023,  1.05157306, -1.05349712,  1.03231169,  0.78615576,
       -0.21577474, -0.4804175 ,  0.39514422,  0.40011795,  0.35015934,
        0.82505481,  0.28981012, -1.39185819,  0.48117346,  0.5902999 ,
        2.24800591, -0.16483502,  1.01348636,  1.10294437,  0.48258647,
       -0.52159341,  1.69555267,  0.84659658, -0.80225351, -0.3447367 ,
        1.82062728,  0.38332241,  0.90945024, -1.10345518,  1.16010544,
       -0.2983205 , -1.76831978,  0.47308996,  0.02838899,  0.3808321 ,
       -2.12590793, -0.64113505, -1.62048262, -0.17203345, -0.79