In [2]:
import numpy as np

In [4]:
mat1=np.array(1)
print ("elements:",mat1)
print("dimn",mat1.ndim)

elements: 1
dimn 0


In [26]:
# 1d mat:
d1=np.array([1,2,3])
d2=np.array([3,4,5])


for i in range(len(d1)):
    for j in range(len(d2)):
         print(d1[i]*d2[j])

3
4
5
6
8
10
9
12
15


In [3]:
# 1d mat:
d1=np.array([1,2,3])
d2=np.array([3,4,5])

res=0
for i in range(len(d1)):
    ress=d1[i]*d2[i]
    res+=ress 


print (res)

26


In [12]:
d2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
d2.shape

(2, 5)

In [16]:
d2=np.array([[[1,2,3,4,5],[2,3,4,5,6],[2,3,4,5,6]],[[1,2,3,4,5],[2,3,4,5,6],[2,3,4,5,6]]])
d2.shape

(2, 3, 5)

In [18]:
array=np.random.rand(4,5)
array

array([[0.77812575, 0.30125128, 0.14441695, 0.34318232, 0.06702559],
       [0.10034336, 0.99189262, 0.71957864, 0.42269029, 0.67795783],
       [0.26342933, 0.96410563, 0.49289753, 0.996797  , 0.0542891 ],
       [0.64529112, 0.78823693, 0.92390765, 0.04626416, 0.41843629]])

In [19]:
array=np.random.rand(3,4,5)
array

array([[[0.44405389, 0.49737034, 0.38841987, 0.55195332, 0.43511448],
        [0.25672597, 0.21884021, 0.19912407, 0.63565555, 0.48034966],
        [0.06881941, 0.37037532, 0.7055746 , 0.68475043, 0.17979551],
        [0.3654975 , 0.09628497, 0.49225922, 0.20851319, 0.32944792]],

       [[0.70729338, 0.84184806, 0.50438023, 0.20089975, 0.05967031],
        [0.62821711, 0.55226541, 0.20718285, 0.62410441, 0.28407672],
        [0.99068664, 0.39224807, 0.23007517, 0.41536059, 0.71393202],
        [0.33947496, 0.8186307 , 0.07586122, 0.30881481, 0.09243341]],

       [[0.20542069, 0.58721181, 0.17865271, 0.79015777, 0.12186634],
        [0.14042606, 0.36328039, 0.63067666, 0.57870342, 0.90861017],
        [0.22827768, 0.41260766, 0.87046776, 0.29269074, 0.17515442],
        [0.12591484, 0.67498643, 0.58894068, 0.44378642, 0.37181556]]])

In [21]:

array=np.random.rand(2,3,2,2)
array


array([[[[0.67663411, 0.21191425],
         [0.35267323, 0.14387627]],

        [[0.34990047, 0.57109953],
         [0.54124632, 0.50431847]],

        [[0.80635147, 0.54797813],
         [0.12644007, 0.96697982]]],


       [[[0.24961414, 0.66773967],
         [0.27896224, 0.30969409]],

        [[0.79423834, 0.71895112],
         [0.33165823, 0.56810833]],

        [[0.15956653, 0.54297924],
         [0.69528866, 0.00317005]]]])